{{- if .Values.kubeflow.dataPreparation.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kubeflow-pipeline.fullname" . }}-dataprep
spec:
  template:
    spec:
      containers:
        - name: dataprep
          image: your-docker-repo/dataprep
          command:
            - "python"
            - "/opt/dataprep.py"
      restartPolicy: OnFailure
{{- end }}
