apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api
  labels:
    app: golang-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: {{ .Values.golangApi.image.repository }}:{{ .Values.golangApi.image.tag }}
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"