apiVersion: v1
kind: Service
metadata:
  name: kubeflow-pipeline
  labels:
    app: kubeflow-pipeline
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
  selector:
    app: kubeflow-pipeline
